[template]
include = ["Cargo.toml", "godot/export_presets.cfg", "godot/native/game.gdnlib", "armory/project.godot", "Makefile.toml", "README.md", "rust/.vscode/launch.json", "rust/Cargo.toml", "shell.nix"]
Footer

