 
# custom.py for godot binary
platform="linuxbsd"
target="release_debug"
tools="yes"
optimize="speed"
use_llvm="yes"
use_lto="yes"
debug_symbols="no"
use_static_cpp="no"
modules_enabled_by_default="no"
deprecated="no"
no_editor_splash="yes"

#modules
module_assimp_enabled = "yes"
module_gridmap_enabled = "yes"
module_opensimplex_enabled = "yes"
module_freetype_enabled="yes"
#module_bmp_enabled = "no"
#module_bullet_enabled = "no"
#module_csg_enabled = "no"
#module_dds_enabled = "no"
#module_enet_enabled = "no"
#module_etc_enabled = "no"
#module_gdnative_enabled = "no"
#module_hdr_enabled = "no"
#module_jsonrpc_enabled = "no"
#module_mbedtls_enabled = "no"
#module_mobile_vr_enabled = "no"
#module_opus_enabled = "no"
#module_pvr_enabled = "no"
#module_recast_enabled = "no"
#module_regex_enabled = "no"
#module_squish_enabled = "no"
#module_svg_enabled = "no"
#module_tga_enabled = "no"
#module_theora_enabled = "no"
#module_tinyexr_enabled = "no"
#module_upnp_enabled = "no"
#module_vhacd_enabled = "no"
#module_vorbis_enabled = "no"
#module_webm_enabled = "no"
#module_webp_enabled = "no"
#module_webrtc_enabled = "no"
#module_websocket_enabled = "no"
#module_xatlas_unwrap_enabled = "no"