#!/usr/bin/env python

import os

# Using godot-cpp as the source of our env
env =  SConscript("../godot-cpp/SConstruct")

# set binaries folder
output_path = "../armory/bin"

if env["platform"] == "windows" :
    cxx_flags = ['/std:c++17', '/Zc:alignedNew']
    cc_flags  = ['/O2'] + ["-EHsc", "-MD"]
else :
    cxx_flags =  ['-std=c++17']
    cc_flags  = ['-O3', '-fPIC', '-static']

# list all modules
mod_list = [d for d in os.listdir() if os.path.isdir(d)]

# build all modules as extensions
for mod_dir in mod_list :   
    env.SConscript(os.path.join(mod_dir, 'SConstruct'), exports=['env','output_path'])
